### ISSUE TITLE
models not showing

### ISSUE THREAD

**Issue by Rogenar** [Iunius118/ToLaserBlade-ExtraModels#1]
Extra models are not visible in v0.0.1 (Fabric) version.

**Comment by Iunius118** [comment]
Please tell me a few things to solve the issue.
- ToLaserBlade version
- Are the models in ToLaserBlade visible?
- Are you using a shader mod?

**Comment by Rogenar** [comment]
I don't use shader mode. Tolaser blade versiyon v1.19.3-0.7.0.4 Fabric. To laser blade 
ToLaserBlade-ExtraModels versiyon 1.19.3 0.0.1versiyon. Extra models are not visible.

**Comment by Iunius118** [comment]
I have not yet reproduced the issue and it may take some time to investigate the cause.
Let me confirm how to reproduce the issue:

1. Get a laser blade
2. Try to change the model of the laser blade with a recipe added by Extra Models mod
3. The laser blade becomes invisible (the issue occurs)

Is the above correct?

**Comment by Rogenar** [comment]
![sd](https://user-images.githubusercontent.com/122460325/214099344-eede3bb3-9748-4a4b-991c-4a6cba50b564.png)
There are only weapons in this image. No extra models. But the mod appears in the menu.
![ds](https://user-images.githubusercontent.com/122460325/214100992-30fe3c57-87d0-46ab-bbbc-28bb7b4efb56.png)

**Comment by Iunius118** [comment]
OK!
Extra models will not be added to the creative inventory because model information is saved in each laser blade item.

If you want to get an extra model laser blade, use an additional recipe for smithing table or use a command.
For example, if you want to get a laser blade of model type 101, do one of the following:

- Upgrade a laser blade with an iron sword on smithing table<br/>![laserblade_ironsword](https://user-images.githubusercontent.com/18502177/214147397-e19e14e4-e3d5-4a6d-b8a5-0dffe853f040.png)
- Use a command (cheat mode or op required): `/give @p tolaserblade:laser_blade{type:101}`

**Comment by Rogenar** [comment]
I did what you said and it worked. But there are 2 strange situations. first, extra laser blade versions must be in the creative inventory. Because players use mods such as jei or rei to access item recipes more easily. secondly, extra laser swords must have a stat difference in damage, attack speed, and attack range. Because they are upgraded with different items. I think this mod can be developed further and be a great mod.

**Comment by Iunius118** [comment]
Thanks for your suggestion.
I would like to add the creative inventory to my future plans. However, I don't intend to add performance difference to each model. This is because Extra Models mod changes the laser blade model through a skin-like mechanism that does not affect the performance of the laser blade. I plan to keep this mechanism the same to keep adding models easy.
